require("modules.world-loot.prototypes.basic-cache.item")
require("modules.world-loot.prototypes.basic-cache.entity")
require("modules.world-loot.prototypes.rare-cache.item")
require("modules.world-loot.prototypes.rare-cache.entity")
require("modules.world-loot.prototypes.epic-cache.item")
require("modules.world-loot.prototypes.epic-cache.entity")
require("modules.world-loot.prototypes.legendary-cache.item")
require("modules.world-loot.prototypes.legendary-cache.entity")
