local recipe = require('util.data-recipe')
local technology = require('util.data-technology')

recipe.disable('science-pack-1')
recipe.disable('science-pack-2')
recipe.disable('science-pack-3')
recipe.disable('alien-science-pack')

technology.remove('research-effectivity-1')
technology.remove('research-effectivity-2')
technology.remove('research-effectivity-3')
technology.remove('research-effectivity-4')
technology.replace_science_pack_from_all('science-pack-1', 'quantum-crystal')
technology.remove_science_pack_from_all('science-pack-2')
technology.remove_science_pack_from_all('science-pack-3')
technology.remove_science_pack_from_all('alien-science-pack')
