require("modules.research-station.prototypes.quantum-crystal.item")
require("modules.research-station.prototypes.quantum-vein.resource")
require("modules.research-station.prototypes.research-station.item")
require("modules.research-station.prototypes.research-station.entity")
require("modules.research-station.prototypes.research-station.recipe")
